name: 游냍 Bug Report
description: Rapporter en feil i FS
title: "[BUG] "
type: ["bug"]
body:
  - type: textarea
    id: bug_description
    attributes:
      label: Beskrivelse av feil
      description: En tydelig og kortfattet beskrivelse av feilen
      placeholder: |
        Beskriv feilen som oppst친r:
        - Hva skjer som ikke skal skje?
        - N친r oppst친r feilen?
        - Hvilke deler av systemet er p친virket?
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steg for 친 reprodusere
      description: Steg-for-steg instruksjoner for 친 gjenskape feilen
      placeholder: |
        1. G친 til '...'
        2. Klikk p친 '...'
        3. Skriv inn '...'
        4. Se feilmeldingen
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Forventet oppf칮rsel
      description: En tydelig beskrivelse av hva du forventet skulle skje
      placeholder: Beskriv hva som skulle ha skjedd i stedet...
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Faktisk oppf칮rsel
      description: Hva skjer i stedet for det forventede
      placeholder: Beskriv n칮yaktig hva som skjer...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Prioritet
      description: Hvor kritisk er denne feilen?
      options:
        - low - Mindre feil som ikke p친virker hovedfunksjonalitet
        - medium - Feil som p친virker funksjonalitet men har workaround
        - high - Feil som betydelig p친virker brukere eller system
        - critical - Kritisk feil som stopper produksjon eller sikkerhet
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Alvorlighetsgrad
      description: Hvor mange brukere/prosesser p친virkes?
      options:
        - Lav - P친virker enkeltbrukere sporadisk
        - Middels - P친virker noen brukere regelmessig
        - H칮y - P친virker mange brukere eller kritiske prosesser
        - Kritisk - P친virker alle brukere eller systemstabilitet
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Milj칮
      description: Hvor oppdages feilen?
      placeholder: |
        - Milj칮: (test/staging/produksjon)
        - Nettleser: (hvis relevant)
        - Operativsystem: (hvis relevant)
        - Versjon/branch: (hvis kjent)
    validations:
      required: false

  - type: textarea
    id: error_logs
    attributes:
      label: Feilmeldinger/Logger
      description: Eventuelle feilmeldinger, stack traces eller logger
      placeholder: |
        Lim inn eventuelle:
        - Feilmeldinger fra brukergrensesnittet
        - Logger fra serveren
        - Nettleser-konsoll feil
        - Stack traces
      render: text
    validations:
      required: false

  - type: textarea
    id: workaround
    attributes:
      label: Midlertidig l칮sning
      description: Er det noen m친te 친 omg친 feilen p친?
      placeholder: Beskriv eventuelle workarounds eller midlertidige l칮sninger...
    validations:
      required: false

  - type: checkboxes
    id: impact_areas
    attributes:
      label: P친virkede omr친der
      description: Hvilke deler av systemet p친virkes?
      options:
        - label: Brukergrensesnitt/Frontend
          required: false
        - label: Backend/API
          required: false
        - label: Database
          required: false
        - label: Integrasjoner
          required: false
        - label: Sikkerhet
          required: false
        - label: Ytelse
          required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Tilleggsinformasjon
      description: Legg til eventuelle skjermbilder eller annen kontekst
      placeholder: |
        - Skjermbilder av feilen
        - Relaterte issues
        - N친r feilen f칮rst ble oppdaget
        - Frekvens av feilen
    validations:
      required: false