name: 🚀 Ny funksjonalitet
description: Foreslå ny funksjonalitet for FS
title: "[FEATURE] "
labels: ["type:feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Beskrivelse
      description: Kort beskrivelse av hva som ønskes utviklet
      placeholder: Beskriv den nye funksjonaliteten som ønskes utviklet
    validations:
      required: true
  
  - type: textarea
    id: user_value
    attributes:
      label: Brukerhistorie (eller enkel kravspek EARS)
      description: Definer verdien for brukeren, eller systemet skal realisere
      placeholder: |
        Som [rolle/system] ønsker jeg [funksjonalitet] slik at [nytte]
        
        Eksempel:
        Som administrator ønsker jeg å kunne filtrere studenter etter studieprogram slik at jeg raskere kan finne relevante studentgrupper.
    validations:
      required: true

  - type: textarea
    id: feature_parts
    attributes:
      label: Delleveranser
      description: Nødvendige leveranser for at funksjonaliteten kan brukes
      placeholder: |
        - [ ] del 1
        - [ ] del 2  
        - [ ] del 3
      value: |
        - [ ] 
        - [ ] 
        - [ ] 
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Tilleggsinformasjon
      description: Legg til eventuelle skjermbilder, wireframes, eller annen kontekst
      placeholder: |
        - Lenker til relaterte issues
        - Skjermbilder eller mockups
        - Referanser til funksjonelle krav
    validations:
      required: false
