name: 游 Feature Initiativ
description: Denne malen brukes til 친 beskrive initiativer som skal i veikart
title: "[TITTEL P칀 INITIATIV] "
labels: ["type:feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Beskrivelse
      description: Kort beskrivelse av utviklingsinitiativet
      placeholder: Beskriv hva initiativet g친r ut p친 og hvorfor det er viktig
    validations:
      required: true
  
  - type: textarea
    id: user_value
    attributes:
      label: Hvilke problem eller behov l칮ser initiativet og for hvem?
      description: Definer verdien for kunde og/eller bruker
      placeholder: |
        - Problem/behov
        - m친lgruppe
        

    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Suksesskriterier
      description: Konkrete kriterier som m친 oppfylles for at funksjonaliteten er ferdig
      placeholder: |
        - [ ] Kriterium 1
        - [ ] Kriterium 2  
        - [ ] Kriterium 3
      value: |
        - [ ] 
        - [ ] 
        - [ ] 
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Prioritet
      description: Hvor viktig er dette initiativet?
      options:
        - low
        - medium
        - high
        - critical
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Tilleggsinformasjon
      description: Legg til eventuelle skjermbilder, wireframes, eller annen kontekst
      placeholder: |
        - Lenker til relaterte issues
        - Skjermbilder eller mockups
        - Referanser til funksjonelle krav
    validations:
      required: false

  - type: textarea
    id: technical_notes
    attributes:
      label: Tekniske notater
      description: Eventuelle tekniske krav, betraktninger eller avhengigheter
      placeholder: |
        - Ber칮rte applikasjoner/tjenester
        - Avhengigheter til andre systemer
        - Tekniske utfordringer
        - Foresl친tte l칮sningsmetoder
    validations:
      required: false

  - type: checkboxes
    id: definition_of_done
    attributes:
      label: Definisjon av ferdig
      description: Standard sjekkliste for n친r en feature regnes som ferdig
      options:
        - label: Brukertesting gjennomf칮rt
          required: false
        - label: Kode utviklet og testet
          required: false
        - label: Akseptansetester kj칮rt og godkjent
          required: false
        - label: Dokumentasjon og utgivelsesnotater oppdatert
          required: false
        - label: Tilgjengelig for brukere i produksjon
          required: false
        - label: Sikkerhetsvurdering gjennomf칮rt (hvis aktuelt)
          required: false
        - label: Tilgangsstyring konfigurert (hvis aktuelt)
          required: false
