name: 游댢 Vedlikehold og drift
description: Teknisk gjeld, vedlikehold og oppgraderinger (BAU/HART-aktiviteter)
title: "[MAINTENANCE] "
labels: ["type:maintenance"]
body:
  - type: dropdown
    id: maintenance_type
    attributes:
      label: Type vedlikehold
      description: Hvilken type vedlikehold gjelder dette?
      options:
        - Teknisk gjeld
        - Oppgradering av avhengigheter
        - Refaktorering
        - Sikkerhetspatch
        - Ytelsesoptimalisering  
        - Dokumentasjon
        - Testing/testdekning
        - CI/CD forbedringer
        - drift
        - Databaseoppgradering
    validations:
      required: true

  - type: textarea
    id: current_state
    attributes:
      label: N친v칝rende tilstand
      description: Beskrivelse av det som trenger vedlikehold
      placeholder: |
        Beskriv n친v칝rende situasjon:
        - Hva er problemet med dagens l칮sning?
        - Hvorfor trenger det vedlikehold?
        - Hvilke risikoer finnes hvis dette ikke gj칮res?
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Fordeler ved vedlikeholdet
      description: Hvilken verdi gir dette arbeidet?
      placeholder: |
        Fordeler ved 친 gj칮re dette arbeidet:
        - [ ] Redusert teknisk gjeld
        - [ ] Forbedret sikkerhet  
        - [ ] Bedre ytelse
        - [ ] Enklere vedlikehold fremover
        - [ ] Forbedret utvikleropplevelse
        - [ ] 칒kt systemstabilitet
      value: |
        - [ ] 
        - [ ] 
        - [ ] 
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Prioritet
      description: Hvor viktig er dette vedlikeholdet?
      options:
        - low - Kan gj칮res n친r det passer
        - medium - B칮r gj칮res innen rimelig tid
        - high - Viktig for systemkvalitet
        - critical - M친 gj칮res snart (sikkerhet/stabilitet)
    validations:
      required: false

  - type: textarea
    id: testing_requirements
    attributes:
      label: Testkrav
      description: Hva m친 testes n친r arbeidet er ferdig?
      placeholder: |
        Testingkrav:
        - Automatiske tester som m친 oppdateres/lages
        - Manuell testing som m친 utf칮res  
        - Regresjonstesting som trengs
        - Ytelsetesting (hvis aktuelt)
    validations:
      required: false

  - type: textarea
    id: additional_notes
    attributes:
      label: Tilleggsnotater
      description: Annen relevant informasjon
      placeholder: |
        - Lenker til relevant dokumentasjon
        - Avhengigheter til andre saker
        - Tidspunkt n친r arbeidet b칮r gj칮res
        - Koordinering som trengs
    validations:
      required: false
