name: 游댢 Maintenance
description: Teknisk gjeld, vedlikehold og oppgraderinger
title: "[MAINTENANCE] "
labels: ["type:maintenance"]
body:
  - type: dropdown
    id: maintenance_type
    attributes:
      label: Type vedlikehold
      description: Hvilken type vedlikehold gjelder dette?
      options:
        - Teknisk gjeld
        - Oppgradering av avhengigheter
        - Refaktorering
        - Sikkerhet patch
        - Ytelsesoptimalisering  
        - Dokumentasjon
        - Testing/testdekning
        - CI/CD forbedringer
    validations:
      required: true

  - type: textarea
    id: current_state
    attributes:
      label: N친v칝rende tilstand
      description: Beskrivelse av det som trenger vedlikehold
      placeholder: |
        Beskriv n친v칝rende situasjon:
        - Hva er problemet med dagens l칮sning?
        - Hvorfor trenger det vedlikehold?
        - Hvilke risikoer finnes hvis dette ikke gj칮res?
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Foresl친tt l칮sning
      description: Hvordan skal vedlikeholdet utf칮res?
      placeholder: |
        Beskriv tiln칝rmingen:
        - Konkrete steg som skal gj칮res
        - Tekniske valg og begrunnelser
        - Alternative l칮sninger vurdert
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Fordeler ved vedlikeholdet
      description: Hvilken verdi gir dette arbeidet?
      placeholder: |
        Fordeler ved 친 gj칮re dette arbeidet:
        - [ ] Redusert teknisk gjeld
        - [ ] Forbedret sikkerhet  
        - [ ] Bedre ytelse
        - [ ] Enklere vedlikehold fremover
        - [ ] Forbedret utvikleropplevelse
        - [ ] 칒kt systemstabilitet
      value: |
        - [ ] 
        - [ ] 
        - [ ] 
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Prioritet
      description: Hvor viktig er dette vedlikeholdet?
      options:
        - low - Kan gj칮res n친r det passer
        - medium - B칮r gj칮res innen rimelig tid
        - high - Viktig for systemkvalitet
        - critical - M친 gj칮res snart (sikkerhet/stabilitet)
    validations:
      required: false

  - type: dropdown
    id: complexity
    attributes:
      label: Estimert kompleksitet
      description: Hvor komplisert er dette arbeidet?
      options:
        - Lav - Noen timer til 1 dag
        - Middels - 1-3 dager  
        - H칮y - 1-2 uker
        - Meget h칮y - Flere uker eller m친neder
    validations:
      required: false

  - type: checkboxes
    id: risk_factors
    attributes:
      label: Risikofaktorer
      description: Hva m친 vurderes ved dette arbeidet?
      options:
        - label: P친virker produksjonssystem
          required: false
        - label: Krever database-migrering
          required: false
        - label: P친virker integrasjoner
          required: false  
        - label: Krever koordinering med andre team
          required: false
        - label: Kan p친virke brukere midlertidig
          required: false
        - label: Krever testing av hele systemet
          required: false

  - type: textarea
    id: testing_requirements
    attributes:
      label: Testingkrav
      description: Hva m친 testes n친r arbeidet er ferdig?
      placeholder: |
        Testingkrav:
        - Automatiske tester som m친 oppdateres/lages
        - Manuell testing som m친 utf칮res  
        - Regresjonstesting som trengs
        - Ytelsetesting (hvis aktuelt)
    validations:
      required: false

  - type: textarea
    id: additional_notes
    attributes:
      label: Tilleggsnotater
      description: Annen relevant informasjon
      placeholder: |
        - Lenker til relevant dokumentasjon
        - Avhengigheter til andre saker
        - Tidspunkt n친r arbeidet b칮r gj칮res
        - Koordinering som trengs
    validations:
      required: false